version: '2.4'

services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=3000
    command: nodemon index.js
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/node_app/app:delegated
      - notused:/opt/node_app/node_modules

  docs:
    image: redocly/redoc:v2.0.0-rc.8-1
    ports:
      - '3001:80'
    volumes:
      - ./src/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      - SPEC_URL=openapi.yml

volumes:
  notused:
    driver: local
