version: '2.4'

services:
  server:
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=$PORT
    command: nodemon src/index.js
    ports:
      - '$PORT:$PORT'
    volumes:
      - .:/opt/node_app/app:delegated
      - notused:/opt/node_app/node_modules
    env_file: .env

  mongo:
    image: mongo:4
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'

  docs:
    image: redocly/redoc:v2.0.0-rc.8-1
    ports:
      - '3001:80'
    volumes:
      - ./src/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      - SPEC_URL=openapi.yml

volumes:
  notused:
  db-data:
